# Generated by Django 5.0.1 on 2024-01-06 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Upload_Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('image_type', models.CharField(choices=[('portrait', 'portrait'), ('Landscape', 'Landscape')], max_length=70)),
            ],
        ),
    ]
